name: CI

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  NODE_OPTIONS: --max-old-space-size=16384

permissions: write-all

jobs:
  release:
    name: Generate release
    if: ${{ github.event.pull_request.merged && github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install commit-and-tag-version

      - name: Get tag name for release
        id: get_tag_name
        run: |
          TAG_NAME=$(npx commit-and-tag-version --skip.changelog --skip.commit --dry-run | grep 'tagging release' | awk '{print $NF}')
          echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Bump version and commit
        run: |
          npx commit-and-tag-version --bumpFiles: package.json --skip.changelog --skip.commit
          git add package.json
          git commit -m "chore(release): bump version to ${{ steps.get_tag_name.outputs.tag }}"

      - name: Push changes to a temporary branch
        id: branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TEMP_BRANCH="release-$(date +%Y%m%d%H%M%S)"
          echo "branch=$TEMP_BRANCH" >> "$GITHUB_OUTPUT"
          git push --follow-tags origin HEAD:$TEMP_BRANCH

      - name: Create PR to main
        id: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          PR_NUMBER=$(gh pr create \
            --title "Automated bump version ${{ steps.get_tag_name.outputs.tag }}" \
            --body "Bump version to ${{ steps.get_tag_name.outputs.tag }}" \
            --base main \
            --head "${{ steps.branch.outputs.branch }}" \
            --json number -q .number)
          if [ -z "$PR_NUMBER" ]; then
            echo "Failed to create PR"
            echo $PR_RESPONSE
            exit 1
          fi
          echo "Pull Request created: $PR_NUMBER"
          echo "PR=$PR_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Merge pull request with admin rights
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.pr.outputs.PR }} --squash --admin

      - name: Publish release with auto-generated notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.get_tag_name.outputs.tag }}" \
            --title "${{ steps.get_tag_name.outputs.tag }}" \
            --generate-notes \
            --target main
  generate-changelog:
    needs: [release]
    uses: ReggiardoJuan/seleniumNode/.github/workflows/changelog.yml@main
