name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

env:
  NODE_OPTIONS: --max-old-space-size=16384

jobs:
  validate_azure_task_presence:
    name: Validate Azure task is present in PR body
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - id: print pull
      name: Get task id from associated pull request
      run: |
          echo ${{ toJson(github) }};
      - id: task
        name: Get task-id from body comment
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const body = ${{ toJson(github.event.pull_request.body) }};
            const azureTask = body?.match(/(?<=AB#)[0-9]+/);
            if (!azureTask) {
              core.setFailed('Azure task presence validation fail');
            }


  update_board_task_status:
    name: Update board task status on PR merge
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - id: print pull
      name: Get task id from associated pull request
      run: |
          echo ${{ toJson(github) }};
      - id: get_pr
        name: Get task id from associated pull request
        run: |
            pullRequest="$(gh api /repos/$REPOSITORY/commits/$EVENT_SHA/pulls)"
            echo "PULL_REQUEST=$pullRequest" >> $GITHUB_ENV
        env:
            REPOSITORY: ${{ github.repository }}
            EVENT_SHA: ${{ github.sha }}
            GH_TOKEN: ${{ secrets.TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
            pip install requests
      - name: Run script
        run: |
            python .github/scripts/update_board.py
        env:
            # ADO_TOKEN: ${{ secrets.ADO_TOKEN }}
            PULL_REQUEST: ${{ env.PULL_REQUEST }}
            NEW_STATE: 'Done'

