version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/" # Location of package manifests
      schedule:
        interval: "daily"
        # Check for npm updates at 9am UTC
        time: "18:20"
        timezone: "America/Argentina/Buenos_Aires"